### ISSUE TITLE
taro 引入 dva 报错

### ISSUE THREAD

**Issue by crazyCode2** [zcSkr/taro-dva-wxParse#1]
你好，我运行你的项目，报错：Cannot read property 'createTextNode' of undefined 
TypeError: Cannot read property 'createTextNode' of undefined ，请问是因为什么导致的，谢谢

**Comment by zcSkr** [comment]
我下载了项目，跑起来之后没有复现您说的这个问题，您可以clone下https://github.com/zuoge85/taro-dva
这个项目 也是taro+dva的仿知乎例子看能不能跑起来，我在此基础上 增加了富文本解析。

**Comment by zcSkr** [comment]
> 你好，我运行你的项目，报错：Cannot read property 'createTextNode' of undefined
> TypeError: Cannot read property 'createTextNode' of undefined ，请问是因为什么导致的，谢谢

我下载了项目，跑起来之后没有复现您说的这个问题，您可以clone下https://github.com/zuoge85/taro-dva
这个项目 也是taro+dva的仿知乎例子看能不能跑起来，我在此基础上 增加了富文本解析。
